name: bvg_departures
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  google_fonts: ^6.3.0
  flutter_svg: ^2.2.0
  go_router: ^16.2.0
  get_it: ^8.2.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializer: ^0.2.0
  flutter_gen_runner: ^5.11.0
  flutter_bloc: ^9.1.1

flutter:

  uses-material-design: true

  assets:
    - assets/icons/arrow_left_alt.svg
    - assets/icons/cancel.svg
    - assets/icons/chevron_right.svg
    - assets/icons/close.svg
    - assets/icons/explore_nearby.svg
    - assets/icons/placeholder.svg
    - assets/icons/search.svg
    - assets/transporters/
